stages:
    - build
    - deploy
    - destroy

build:
    stage: build
    script:
        - docker info
        - mkdir gopath
        - export GOROOT=/usr/local/go
        - export GOPATH=/usr/local/gopath
        - go get github.com/gin-gonic/gin  
        - go get github.com/mattn/go-sqlite3 
        - go get github.com/fatih/structs 
        - go get github.com/jinzhu/gorm 
        - go get github.com/robvdl/pongo2gin 
        - go get github.com/thinkerou/favicon 
        - go get github.com/flosch/pongo2 
        - go get github.com/russross/blackfriday 
        - go get github.com/microcosm-cc/bluemonday 
        - go build
    tags:
        - docker

deploy:
    when: manual
    stage: deploy
    script:
        - mkdir build
        - export GOPATH=/usr/local/gopath
        - go get github.com/gin-gonic/gin  
        - go get github.com/mattn/go-sqlite3 
        - go get github.com/fatih/structs 
        - go get github.com/jinzhu/gorm 
        - go get github.com/robvdl/pongo2gin 
        - go get github.com/thinkerou/favicon 
        - go get github.com/flosch/pongo2 
        - go get github.com/russross/blackfriday 
        - go get github.com/microcosm-cc/bluemonday 
        - go build 
        - mv Captains_Log build/
        - echo '{"port":"443","database":"/blog/blog.db","username":"$USERNAME","password":"$PASSWORD","logfile":"/blog/blog.log","html":"./templates"}' > ./build/config.json
        - docker-compose up -d 
    tags:
        - docker

destroy:
    when: manual
    stage: destroy
    script:
        - docker stop blog
        - docker rm blog
    tags: 
        - docker

