version: "3"
services:
    webpage:
        image: 'alpine:latest'
        restart: always
        container_name: blog
        hostname: 'blog.philgore.net'
        environment:
            VIRTUAL_HOST: 'blog.philgore.net'
            LETSENCRYPT_EMAIL: 'erog38@gmail.com'
            LETSENCRYPT_HOST: 'blog.philgore.net'
        expose:
            - 443
        volumes:
            - './build:/app'
            - '/opt/blog:/blog'
        command:
            - '/app/Captains_Log /app/config.json'
networks:
    default:
        external:
            name: nginx-net
